title: Avishek Das
url: "https://avishekdas.net"
baseurl: "/new_portfoio"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/new_portfoio/"
 - name: "Education"
   link: "education"
 - name: "Experience"
   link: "experience"
 - name: "Publication"
   link: "publication"
 - name: "Projects"
   link: "projects"
 - name: "Skills"
   link: "skills"
 - name: "Contact"
   link: "contact"
