backend:
  name: github
  repo: avishek-018/avishek-018.github.io
  branch: main
  base_url: https://decap-oauth-render.onrender.com
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "publications"
    label: "Publications"
    folder: "_publications"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "string" }
      - { label: "Venue", name: "venue", widget: "string" }
      - { label: "Venue URL", name: "venue_url", widget: "string", required: false }
      - { label: "Paper URL", name: "paper_url", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "select", options: ["Journal", "Conference"] }
